### ISSUE TITLE
When running Named Entity Recognition script, get "has no attribute Optimizer error"

### ISSUE THREAD

**Issue by demongolem** [dmis-lab/biobert#68]
Here is my trace

> Traceback (most recent call last):
>   File "run_ner.py", line 15, in <module>
>     import optimization
>   File "/Users/gwerner/biobert/optimization.py", line 87, in <module>
>     class AdamWeightDecayOptimizer(tf.train.Optimizer):
> AttributeError: module 'tensorflow_core._api.v2.train' has no attribute 'Optimizer'

I am running the script on the GitHub page under the NER section which is:

`mkdir /tmp/bioner/`

`python3 run_ner.py \
    --do_train=true \
    --do_eval=true \
    --vocab_file=$BIOBERT_DIR/vocab.txt \
    --bert_config_file=$BIOBERT_DIR/bert_config.json \
    --init_checkpoint=$BIOBERT_DIR/biobert_model.ckpt \
    --num_train_epochs=10.0 \
    --data_dir=$NER_DIR/ \
    --output_dir=/tmp/bioner/`

**Comment by demongolem** [comment]
So obviously, this is a case not being Tensorflow 2.0 compatible.  I tried, just for the fun of it, to see how far I could get by transforming the code so that it would work with 2.0, but when I got to LayerNormalization and layer_norm(), that is when things are not quite so automatic any more.

Now, this issue could be solved by changing the requirements.txt file because if I do a pip install from the requirements file, it will give me 2.0 of tensorflow.

**Comment by jhyuklee** [comment]
Thanks for letting us know! We will change the requirements.txt unless we make the code compatible on tf 2.0.

**Comment by ibrahimishag** [comment]
> Thanks for letting us know! We will change the requirements.txt unless we make the code compatible on tf 2.0.

Has anyone converted the source code into a version compatible with TF 2.0?

**Comment by jhyuklee** [comment]
We have fixed the requirements.txt to TF 1.1 version.
